# Generated by Django 4.2.18 on 2026-05-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topTitle', models.CharField(default='About Us', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subdescription', models.TextField(default='No description')),
            ],
        ),
        migrations.CreateModel(
            name='About_Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField(default='No description')),
                ('description2', models.TextField(default='No description')),
                ('description3', models.TextField(default='No description')),
                ('image', models.ImageField(upload_to='Culture/')),
                ('pdf', models.FileField(upload_to='about_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='About_Hill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField(default='No description')),
                ('description2', models.TextField(default='No description')),
                ('description3', models.TextField(default='No description')),
                ('youtube_link', models.URLField(blank=True, null=True, unique=True)),
                ('pdf', models.FileField(upload_to='about_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='About_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Culture/')),
            ],
        ),
        migrations.CreateModel(
            name='About_Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description1', models.TextField(blank=True, default='No description', null=True)),
                ('description2', models.TextField(blank=True, default='No description', null=True)),
                ('image', models.ImageField(blank=True, null=True, unique=True, upload_to='Temple/')),
                ('video1', models.FileField(blank=True, null=True, upload_to='Temple_videos/')),
                ('video2', models.FileField(blank=True, null=True, upload_to='Temple_videos/')),
                ('video3', models.FileField(blank=True, null=True, upload_to='Temple_videos/')),
                ('video4', models.FileField(blank=True, null=True, upload_to='Temple_videos/')),
                ('pdf', models.FileField(blank=True, null=True, unique=True, upload_to='about_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='All_Gellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_gellery_photo/')),
            ],
            options={
                'verbose_name': 'Gallery_Image',
                'verbose_name_plural': 'Gallery_Images',
            },
        ),
        migrations.CreateModel(
            name='All_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='all_video_video/')),
            ],
            options={
                'verbose_name': 'Gallery Video',
                'verbose_name_plural': 'Gallery Videos',
            },
        ),
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('dec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(default='No description', max_length=200)),
                ('description', models.TextField()),
                ('subdescription', models.TextField(default='No description')),
            ],
        ),
        migrations.CreateModel(
            name='Judicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Judicial Title', max_length=200)),
                ('paragraph1', models.TextField(default='No description')),
                ('PDF', models.FileField(upload_to='Judicial/')),
            ],
        ),
        migrations.CreateModel(
            name='Main_docoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph1', models.TextField()),
                ('pdf', models.FileField(upload_to='docoment_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Main_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('paragraph4', models.TextField()),
                ('paragraph5', models.TextField()),
                ('pdf', models.FileField(upload_to='History_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('youtube_link', models.URLField(blank=True, null=True, unique=True)),
                ('news_link', models.URLField(default='No description')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Religen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('image', models.ImageField(upload_to='religen/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumb/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='History/')),
                ('main_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.main_history')),
            ],
        ),
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.about')),
            ],
        ),
    ]
