# Generated by Django 4.2.18 on 2026-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='images',
            field=models.ImageField(default='No description', upload_to='event_all/'),
        ),
    ]
