# Generated by Django 4.2.18 on 2026-06-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_videogallery_thumbnail_videogallery_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Santhal_jain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('image', models.ImageField(upload_to='santhal_jain/')),
                ('PDF', models.FileField(upload_to='santhal_jain/')),
            ],
        ),
    ]
