# Generated by Django 4.2.18 on 2026-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_santhal_jain'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(default='No description', upload_to='Histye/'),
        ),
    ]
